import 'package:flutter/widgets.dart';

import '../models/broker_models.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('ru'),
    Locale('es'),
    Locale('fr'),
    Locale('de'),
    Locale('zh'),
    Locale('ar'),
  ];

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    if (value == null) {
      return AppLocalizations(const Locale('en'));
    }
    return value;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'MQTT HUB',
      'brokers': 'Brokers',
      'importExport': 'Import / Export',
      'debug': 'Debug',
      'settings': 'Settings',
      'refreshNetwork': 'Refresh network snapshot',
      'createBroker': 'Create broker',
      'portInUse': 'Port already in use by another broker.',
      'networkSnapshot': 'Network Snapshot',
      'mode': 'Mode',
      'localIp': 'Local IP',
      'publicIp': 'Public IP',
      'wifi': 'Wi-Fi',
      'unavailable': 'Unavailable',
      'unknown': 'Unknown',
      'noBrokers':
          'No brokers created yet. Use Create broker to start isolated MQTT rooms on the iPhone.',
      'port': 'Port',
      'clients': 'Clients',
      'lastActivity': 'Last activity',
      'noActivity': 'No activity',
      'start': 'Start',
      'stop': 'Stop',
      'restart': 'Restart',
      'open': 'Open',
      'edit': 'Edit',
      'duplicate': 'Duplicate',
      'delete': 'Delete',
      'save': 'Save',
      'deleteBroker': 'Delete broker',
      'cancel': 'Cancel',
      'overview': 'Overview',
      'logs': 'Logs',
      'brokerSettings': 'Broker Settings',
      'brokerNotFound': 'Broker not found',
      'exportBrokerConfig': 'Export broker config',
      'editBroker': 'Edit broker',
      'general': 'General',
      'brokerName': 'Broker name',
      'description': 'Description',
      'currentUptime': 'Current uptime',
      'currentStatus': 'Current status',
      'security': 'Security',
      'network': 'Network',
      'automationLogging': 'Automation + Logging',
      'logging': 'Logging',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'anonymousMode': 'Anonymous mode',
      'username': 'Username',
      'password': 'Password',
      'allowedClients': 'Allowed clients',
      'deniedClients': 'Denied clients',
      'notSet': 'Not set',
      'anyClient': 'Any client',
      'none': 'None',
      'autoStart': 'Auto-start',
      'autoStopTimer': 'Auto-stop timer',
      'autoRestartCrash': 'Auto-restart on crash',
      'scheduledStart': 'Scheduled start',
      'scheduledStop': 'Scheduled stop',
      'logSizeLimit': 'Log size limit',
      'savePayloads': 'Save payloads',
      'websocketPlaceholder': 'Enable WebSocket placeholder',
      'configPersistedLater': 'Config is persisted for later implementation.',
      'allowExternalAccess': 'Allow external access',
      'localNetworkOnly': 'Local network only',
      'hotspotSupport': 'Hotspot mode support',
      'autoStartOnLaunch': 'Auto-start on launch',
      'autoRestartOnCrash': 'Auto-restart on crash',
      'enableLogs': 'Enable logs',
      'allowClientList': 'Allow client list',
      'denyClientList': 'Deny client list',
      'autoStopMinutesLabel': 'Auto-stop timer (minutes)',
      'scheduledStartOptional': 'Scheduled start (optional)',
      'scheduledStopOptional': 'Scheduled stop (optional)',
      'searchLogs': 'Search logs',
      'resumeLogs': 'Resume logs',
      'pauseLogs': 'Pause logs',
      'clearLogs': 'Clear logs',
      'exportLogs': 'Export logs',
      'all': 'All',
      'loggingEnabled': 'Logging enabled',
      'loggingDisabledSystem': 'Logging disabled except system events',
      'client': 'Client',
      'jsonImportExport': 'JSON import/export',
      'exportAllBrokers': 'Export all brokers',
      'importBrokers': 'Import brokers',
      'exportConfig': 'Export config',
      'importedConfigs': 'Imported {count} broker configurations.',
      'about': 'About',
      'aboutText':
          'MQTT HUB runs lightweight MQTT brokers directly on the iPhone. This build is optimized for iOS first and keeps the project ready for a later Android port under a separate folder.',
      'networkStateWarning':
          'iOS may suspend sockets while the app is backgrounded or the screen is locked. MQTT HUB attempts recovery on wake, but background broker uptime cannot be guaranteed by the OS.',
      'exportsShareDescription':
          'Exports are shared through the iOS share sheet, which allows AirDrop, Files app, and other targets.',
      'networkDiagnostics': 'Network diagnostics',
      'rawPacketMonitor': 'Raw packet monitor',
      'noRawPackets': 'No raw MQTT frames captured yet.',
      'internalBrokerState': 'Internal broker state',
      'language': 'Language',
      'maxBrokers': 'Maximum brokers',
      'messageRetentionHours': 'Message retention (hours)',
      'maxLogEntries': 'Max log entries',
      'appliesToNewBrokers': 'Applied to newly created brokers.',
      'statusRunning': 'Running',
      'statusStopped': 'Stopped',
      'statusStarting': 'Starting',
      'statusError': 'Error',
      'modeOffline': 'Offline',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': 'Hotspot',
      'modeCellular': 'Cellular',
      'modeUnknown': 'Unknown',
      'languageSystem': 'System default',
      'langEn': 'English',
      'langRu': 'Russian',
      'langEs': 'Spanish',
      'langFr': 'French',
      'langDe': 'German',
      'langZh': 'Chinese',
      'langAr': 'Arabic',
      'retry': 'Retry',
      'failedInit': 'Failed to initialize app services.',
    },
    'ru': {
      'appTitle': 'MQTT HUB',
      'brokers': 'Брокеры',
      'importExport': 'Импорт / Экспорт',
      'debug': 'Отладка',
      'settings': 'Настройки',
      'refreshNetwork': 'Обновить сеть',
      'createBroker': 'Создать брокер',
      'portInUse': 'Порт уже используется другим брокером.',
      'networkSnapshot': 'Состояние сети',
      'mode': 'Режим',
      'localIp': 'Локальный IP',
      'publicIp': 'Публичный IP',
      'wifi': 'Wi-Fi',
      'unavailable': 'Недоступно',
      'unknown': 'Неизвестно',
      'noBrokers': 'Брокеры еще не созданы. Нажмите Создать брокер.',
      'port': 'Порт',
      'clients': 'Клиенты',
      'lastActivity': 'Последняя активность',
      'noActivity': 'Нет активности',
      'start': 'Запустить',
      'stop': 'Остановить',
      'restart': 'Перезапустить',
      'open': 'Открыть',
      'edit': 'Изменить',
      'duplicate': 'Дублировать',
      'delete': 'Удалить',
      'save': 'Сохранить',
      'deleteBroker': 'Удалить брокер',
      'cancel': 'Отмена',
      'overview': 'Обзор',
      'logs': 'Логи',
      'brokerSettings': 'Настройки брокера',
      'brokerNotFound': 'Брокер не найден',
      'exportBrokerConfig': 'Экспорт конфигурации',
      'editBroker': 'Изменить брокер',
      'general': 'Общее',
      'brokerName': 'Имя брокера',
      'description': 'Описание',
      'currentUptime': 'Время работы',
      'currentStatus': 'Текущий статус',
      'security': 'Безопасность',
      'network': 'Сеть',
      'automationLogging': 'Автоматизация и логи',
      'logging': 'Логирование',
      'enabled': 'Включено',
      'disabled': 'Выключено',
      'anonymousMode': 'Анонимный режим',
      'username': 'Имя пользователя',
      'password': 'Пароль',
      'allowedClients': 'Разрешенные клиенты',
      'deniedClients': 'Запрещенные клиенты',
      'notSet': 'Не задано',
      'anyClient': 'Любой клиент',
      'none': 'Нет',
      'autoStart': 'Автостарт',
      'autoStopTimer': 'Автостоп',
      'autoRestartCrash': 'Автоперезапуск при сбое',
      'scheduledStart': 'Плановый запуск',
      'scheduledStop': 'Плановая остановка',
      'logSizeLimit': 'Лимит логов',
      'savePayloads': 'Сохранять payload',
      'websocketPlaceholder': 'Включить заглушку WebSocket',
      'configPersistedLater': 'Настройка сохраняется для будущей реализации.',
      'allowExternalAccess': 'Разрешить внешний доступ',
      'localNetworkOnly': 'Только локальная сеть',
      'hotspotSupport': 'Поддержка режима точки доступа',
      'autoStartOnLaunch': 'Автозапуск при старте',
      'autoRestartOnCrash': 'Автоперезапуск при сбое',
      'enableLogs': 'Включить логи',
      'allowClientList': 'Список разрешенных клиентов',
      'denyClientList': 'Список запрещенных клиентов',
      'autoStopMinutesLabel': 'Автостоп (минуты)',
      'scheduledStartOptional': 'Плановый запуск (необязательно)',
      'scheduledStopOptional': 'Плановая остановка (необязательно)',
      'searchLogs': 'Поиск по логам',
      'resumeLogs': 'Продолжить логи',
      'pauseLogs': 'Пауза логов',
      'clearLogs': 'Очистить логи',
      'exportLogs': 'Экспорт логов',
      'all': 'Все',
      'loggingEnabled': 'Логирование включено',
      'loggingDisabledSystem': 'Логирование выключено, кроме системных событий',
      'client': 'Клиент',
      'jsonImportExport': 'JSON импорт/экспорт',
      'exportAllBrokers': 'Экспорт всех брокеров',
      'importBrokers': 'Импорт брокеров',
      'exportConfig': 'Экспорт конфигурации',
      'importedConfigs': 'Импортировано конфигураций: {count}.',
      'about': 'О приложении',
      'aboutText': 'MQTT HUB запускает легковесные MQTT-брокеры прямо на iPhone.',
      'networkStateWarning':
          'iOS может приостановить сокеты, пока приложение находится в фоне или экран заблокирован. MQTT HUB пытается восстановиться после пробуждения, но фоновое время работы брокера не гарантируется ОС.',
      'exportsShareDescription':
          'Экспорты совместно используются через лист общего доступа iOS, что позволяет использовать AirDrop, приложение Files и другие методы.',
      'networkDiagnostics': 'Диагностика сети',
      'rawPacketMonitor': 'Монитор сырых пакетов',
      'noRawPackets': 'Сырые MQTT кадры пока не получены.',
      'internalBrokerState': 'Внутреннее состояние брокера',
      'language': 'Язык',
      'maxBrokers': 'Максимум брокеров',
      'messageRetentionHours': 'Хранение сообщений (часы)',
      'maxLogEntries': 'Максимум записей лога',
      'appliesToNewBrokers': 'Применяется к новым брокерам.',
      'statusRunning': 'Работает',
      'statusStopped': 'Остановлен',
      'statusStarting': 'Запуск',
      'statusError': 'Ошибка',
      'modeOffline': 'Оффлайн',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': 'Точка доступа',
      'modeCellular': 'Сотовая сеть',
      'modeUnknown': 'Неизвестно',
      'languageSystem': 'Системный',
      'langEn': 'Английский',
      'langRu': 'Русский',
      'langEs': 'Испанский',
      'langFr': 'Французский',
      'langDe': 'Немецкий',
      'langZh': 'Китайский',
      'langAr': 'Арабский',
      'retry': 'Повторить',
      'failedInit': 'Не удалось инициализировать сервисы приложения.',
    },
    'es': {
      'appTitle': 'MQTT HUB',
      'brokers': 'Brokers',
      'importExport': 'Importar / Exportar',
      'debug': 'Depuracion',
      'settings': 'Configuracion',
      'refreshNetwork': 'Actualizar estado de red',
      'createBroker': 'Crear broker',
      'portInUse': 'El puerto ya esta en uso por otro broker.',
      'networkSnapshot': 'Estado de red',
      'mode': 'Modo',
      'localIp': 'IP local',
      'publicIp': 'IP publica',
      'wifi': 'Wi-Fi',
      'unavailable': 'No disponible',
      'unknown': 'Desconocido',
      'noBrokers':
        'Aun no hay brokers. Usa Crear broker para iniciar salas MQTT aisladas en el iPhone.',
      'port': 'Puerto',
      'clients': 'Clientes',
      'lastActivity': 'Ultima actividad',
      'noActivity': 'Sin actividad',
      'start': 'Iniciar',
      'stop': 'Detener',
      'restart': 'Reiniciar',
      'open': 'Abrir',
      'edit': 'Editar',
      'duplicate': 'Duplicar',
      'delete': 'Eliminar',
      'save': 'Guardar',
      'deleteBroker': 'Eliminar broker',
      'cancel': 'Cancelar',
      'overview': 'Resumen',
      'logs': 'Registros',
      'brokerSettings': 'Configuracion del broker',
      'brokerNotFound': 'Broker no encontrado',
      'exportBrokerConfig': 'Exportar configuracion del broker',
      'editBroker': 'Editar broker',
      'general': 'General',
      'brokerName': 'Nombre del broker',
      'description': 'Descripcion',
      'currentUptime': 'Tiempo activo actual',
      'currentStatus': 'Estado actual',
      'security': 'Seguridad',
      'network': 'Red',
      'automationLogging': 'Automatizacion y registros',
      'logging': 'Registro',
      'enabled': 'Activado',
      'disabled': 'Desactivado',
      'anonymousMode': 'Modo anonimo',
      'username': 'Usuario',
      'password': 'Contrasena',
      'allowedClients': 'Clientes permitidos',
      'deniedClients': 'Clientes denegados',
      'notSet': 'No definido',
      'anyClient': 'Cualquier cliente',
      'none': 'Ninguno',
      'autoStart': 'Inicio automatico',
      'autoStopTimer': 'Temporizador de parada',
      'autoRestartCrash': 'Reinicio automatico tras fallo',
      'scheduledStart': 'Inicio programado',
      'scheduledStop': 'Parada programada',
      'logSizeLimit': 'Limite de registros',
      'savePayloads': 'Guardar payloads',
      'websocketPlaceholder': 'Habilitar marcador WebSocket',
      'configPersistedLater':
        'La configuracion se guarda para implementacion futura.',
      'allowExternalAccess': 'Permitir acceso externo',
      'localNetworkOnly': 'Solo red local',
      'hotspotSupport': 'Soporte de hotspot',
      'autoStartOnLaunch': 'Iniciar automaticamente al abrir',
      'autoRestartOnCrash': 'Reinicio automatico tras fallo',
      'enableLogs': 'Habilitar registros',
      'allowClientList': 'Lista de clientes permitidos',
      'denyClientList': 'Lista de clientes denegados',
      'autoStopMinutesLabel': 'Parada automatica (minutos)',
      'scheduledStartOptional': 'Inicio programado (opcional)',
      'scheduledStopOptional': 'Parada programada (opcional)',
      'searchLogs': 'Buscar en registros',
      'resumeLogs': 'Reanudar registros',
      'pauseLogs': 'Pausar registros',
      'clearLogs': 'Limpiar registros',
      'exportLogs': 'Exportar registros',
      'all': 'Todos',
      'loggingEnabled': 'Registro activado',
      'loggingDisabledSystem':
        'Registro desactivado excepto eventos del sistema',
      'client': 'Cliente',
      'jsonImportExport': 'Importacion/exportacion JSON',
      'exportAllBrokers': 'Exportar todos los brokers',
      'importBrokers': 'Importar brokers',
      'exportConfig': 'Exportar configuracion',
      'importedConfigs': 'Se importaron {count} configuraciones de broker.',
      'about': 'Acerca de',
      'aboutText':
        'MQTT HUB ejecuta brokers MQTT ligeros directamente en el iPhone.',
      'networkStateWarning':
        'iOS puede suspender sockets mientras la aplicación está en segundo plano o la pantalla está bloqueada. MQTT HUB intenta recuperarse al despertar, pero el tiempo de actividad del broker en segundo plano no puede ser garantizado por el SO.',
      'exportsShareDescription':
        'Las exportaciones se comparten a través de la hoja de compartir de iOS, que permite AirDrop, la aplicación Archivos y otros destinos.',
      'networkDiagnostics': 'Diagnostico de red',
      'rawPacketMonitor': 'Monitor de paquetes en bruto',
      'noRawPackets': 'Aun no se capturaron tramas MQTT en bruto.',
      'internalBrokerState': 'Estado interno del broker',
      'language': 'Idioma',
      'maxBrokers': 'Maximo de brokers',
      'messageRetentionHours': 'Retencion de mensajes (horas)',
      'maxLogEntries': 'Maximo de registros',
      'appliesToNewBrokers': 'Se aplica a brokers nuevos.',
      'statusRunning': 'En ejecucion',
      'statusStopped': 'Detenido',
      'statusStarting': 'Iniciando',
      'statusError': 'Error',
      'modeOffline': 'Sin conexion',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': 'Hotspot',
      'modeCellular': 'Celular',
      'modeUnknown': 'Desconocido',
      'languageSystem': 'Predeterminado del sistema',
      'langEn': 'Ingles',
      'langRu': 'Ruso',
      'langEs': 'Espanol',
      'langFr': 'Frances',
      'langDe': 'Aleman',
      'langZh': 'Chino',
      'langAr': 'Arabe',
      'retry': 'Reintentar',
      'failedInit': 'No se pudieron iniciar los servicios de la aplicacion.',
    },
    'fr': {
      'appTitle': 'MQTT HUB',
      'brokers': 'Brokers',
      'importExport': 'Importer / Exporter',
      'debug': 'Debug',
      'settings': 'Parametres',
      'refreshNetwork': 'Actualiser l etat reseau',
      'createBroker': 'Creer un broker',
      'portInUse': 'Ce port est deja utilise par un autre broker.',
      'networkSnapshot': 'Etat du reseau',
      'mode': 'Mode',
      'localIp': 'IP locale',
      'publicIp': 'IP publique',
      'wifi': 'Wi-Fi',
      'unavailable': 'Indisponible',
      'unknown': 'Inconnu',
      'noBrokers':
        'Aucun broker cree pour le moment. Utilisez Creer un broker pour lancer des salles MQTT isolees sur iPhone.',
      'port': 'Port',
      'clients': 'Clients',
      'lastActivity': 'Derniere activite',
      'noActivity': 'Aucune activite',
      'start': 'Demarrer',
      'stop': 'Arreter',
      'restart': 'Redemarrer',
      'open': 'Ouvrir',
      'edit': 'Modifier',
      'duplicate': 'Dupliquer',
      'delete': 'Supprimer',
      'save': 'Enregistrer',
      'deleteBroker': 'Supprimer le broker',
      'cancel': 'Annuler',
      'overview': 'Vue d ensemble',
      'logs': 'Logs',
      'brokerSettings': 'Parametres du broker',
      'brokerNotFound': 'Broker introuvable',
      'exportBrokerConfig': 'Exporter la configuration du broker',
      'editBroker': 'Modifier le broker',
      'general': 'General',
      'brokerName': 'Nom du broker',
      'description': 'Description',
      'currentUptime': 'Duree de fonctionnement',
      'currentStatus': 'Etat actuel',
      'security': 'Securite',
      'network': 'Reseau',
      'automationLogging': 'Automatisation et logs',
      'logging': 'Journalisation',
      'enabled': 'Active',
      'disabled': 'Desactive',
      'anonymousMode': 'Mode anonyme',
      'username': 'Nom d utilisateur',
      'password': 'Mot de passe',
      'allowedClients': 'Clients autorises',
      'deniedClients': 'Clients refuses',
      'notSet': 'Non defini',
      'anyClient': 'Tout client',
      'none': 'Aucun',
      'autoStart': 'Demarrage auto',
      'autoStopTimer': 'Arret automatique',
      'autoRestartCrash': 'Redemarrage auto en cas de crash',
      'scheduledStart': 'Demarrage planifie',
      'scheduledStop': 'Arret planifie',
      'logSizeLimit': 'Limite des logs',
      'savePayloads': 'Enregistrer les payloads',
      'websocketPlaceholder': 'Activer le placeholder WebSocket',
      'configPersistedLater':
        'La configuration est enregistree pour une implementation ulterieure.',
      'allowExternalAccess': 'Autoriser l acces externe',
      'localNetworkOnly': 'Reseau local uniquement',
      'hotspotSupport': 'Support du mode hotspot',
      'autoStartOnLaunch': 'Demarrage auto au lancement',
      'autoRestartOnCrash': 'Redemarrage auto en cas de crash',
      'enableLogs': 'Activer les logs',
      'allowClientList': 'Liste des clients autorises',
      'denyClientList': 'Liste des clients refuses',
      'autoStopMinutesLabel': 'Arret automatique (minutes)',
      'scheduledStartOptional': 'Demarrage planifie (optionnel)',
      'scheduledStopOptional': 'Arret planifie (optionnel)',
      'searchLogs': 'Rechercher dans les logs',
      'resumeLogs': 'Reprendre les logs',
      'pauseLogs': 'Mettre en pause les logs',
      'clearLogs': 'Effacer les logs',
      'exportLogs': 'Exporter les logs',
      'all': 'Tous',
      'loggingEnabled': 'Journalisation activee',
      'loggingDisabledSystem':
        'Journalisation desactivee sauf evenements systeme',
      'client': 'Client',
      'jsonImportExport': 'Import/export JSON',
      'exportAllBrokers': 'Exporter tous les brokers',
      'importBrokers': 'Importer des brokers',
      'exportConfig': 'Exporter la configuration',
      'importedConfigs': '{count} configurations de broker importees.',
      'about': 'A propos',
      'aboutText':
        'MQTT HUB execute des brokers MQTT legers directement sur iPhone.',
      'networkStateWarning':
        'iOS peut suspendre les sockets tandis que l application est en arrière-plan ou l écran est verrouillé. MQTT HUB tente de récupérer au réveil, mais le temps de fonctionnement du broker en arrière-plan ne peut pas être garanti par l OS.',
      'exportsShareDescription':
        'Les exports sont partagés via la feuille de partage iOS, qui permet AirDrop, l application Fichiers et d autres cibles.',
      'networkDiagnostics': 'Diagnostic reseau',
      'rawPacketMonitor': 'Moniteur de paquets bruts',
      'noRawPackets': 'Aucune trame MQTT brute capturee pour le moment.',
      'internalBrokerState': 'Etat interne du broker',
      'language': 'Langue',
      'maxBrokers': 'Nombre max de brokers',
      'messageRetentionHours': 'Retention des messages (heures)',
      'maxLogEntries': 'Nombre max de logs',
      'appliesToNewBrokers': 'Applique aux nouveaux brokers.',
      'statusRunning': 'En cours',
      'statusStopped': 'Arrete',
      'statusStarting': 'Demarrage',
      'statusError': 'Erreur',
      'modeOffline': 'Hors ligne',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': 'Hotspot',
      'modeCellular': 'Cellulaire',
      'modeUnknown': 'Inconnu',
      'languageSystem': 'Systeme',
      'langEn': 'Anglais',
      'langRu': 'Russe',
      'langEs': 'Espagnol',
      'langFr': 'Francais',
      'langDe': 'Allemand',
      'langZh': 'Chinois',
      'langAr': 'Arabe',
      'retry': 'Reessayer',
      'failedInit': 'Echec de l initialisation des services de l application.',
    },
    'de': {
      'appTitle': 'MQTT HUB',
      'brokers': 'Broker',
      'importExport': 'Import / Export',
      'debug': 'Debug',
      'settings': 'Einstellungen',
      'refreshNetwork': 'Netzwerkstatus aktualisieren',
      'createBroker': 'Broker erstellen',
      'portInUse': 'Der Port wird bereits von einem anderen Broker verwendet.',
      'networkSnapshot': 'Netzwerkstatus',
      'mode': 'Modus',
      'localIp': 'Lokale IP',
      'publicIp': 'Offentliche IP',
      'wifi': 'Wi-Fi',
      'unavailable': 'Nicht verfugbar',
      'unknown': 'Unbekannt',
      'noBrokers':
        'Noch keine Broker erstellt. Nutze Broker erstellen fur isolierte MQTT-Raume auf dem iPhone.',
      'port': 'Port',
      'clients': 'Clients',
      'lastActivity': 'Letzte Aktivitat',
      'noActivity': 'Keine Aktivitat',
      'start': 'Starten',
      'stop': 'Stoppen',
      'restart': 'Neu starten',
      'open': 'Offnen',
      'edit': 'Bearbeiten',
      'duplicate': 'Duplizieren',
      'delete': 'Loschen',
      'save': 'Speichern',
      'deleteBroker': 'Broker loschen',
      'cancel': 'Abbrechen',
      'overview': 'Ubersicht',
      'logs': 'Logs',
      'brokerSettings': 'Broker-Einstellungen',
      'brokerNotFound': 'Broker nicht gefunden',
      'exportBrokerConfig': 'Broker-Konfiguration exportieren',
      'editBroker': 'Broker bearbeiten',
      'general': 'Allgemein',
      'brokerName': 'Broker-Name',
      'description': 'Beschreibung',
      'currentUptime': 'Aktuelle Laufzeit',
      'currentStatus': 'Aktueller Status',
      'security': 'Sicherheit',
      'network': 'Netzwerk',
      'automationLogging': 'Automatisierung und Logging',
      'logging': 'Logging',
      'enabled': 'Aktiviert',
      'disabled': 'Deaktiviert',
      'anonymousMode': 'Anonymer Modus',
      'username': 'Benutzername',
      'password': 'Passwort',
      'allowedClients': 'Erlaubte Clients',
      'deniedClients': 'Gesperrte Clients',
      'notSet': 'Nicht gesetzt',
      'anyClient': 'Beliebiger Client',
      'none': 'Keine',
      'autoStart': 'Auto-Start',
      'autoStopTimer': 'Auto-Stopp-Timer',
      'autoRestartCrash': 'Auto-Neustart bei Absturz',
      'scheduledStart': 'Geplanter Start',
      'scheduledStop': 'Geplanter Stopp',
      'logSizeLimit': 'Log-Limit',
      'savePayloads': 'Payloads speichern',
      'websocketPlaceholder': 'WebSocket-Platzhalter aktivieren',
      'configPersistedLater':
        'Konfiguration wird fur spatere Implementierung gespeichert.',
      'allowExternalAccess': 'Externen Zugriff erlauben',
      'localNetworkOnly': 'Nur lokales Netzwerk',
      'hotspotSupport': 'Hotspot-Modus-Unterstutzung',
      'autoStartOnLaunch': 'Beim Start automatisch starten',
      'autoRestartOnCrash': 'Bei Absturz automatisch neu starten',
      'enableLogs': 'Logs aktivieren',
      'allowClientList': 'Liste erlaubter Clients',
      'denyClientList': 'Liste gesperrter Clients',
      'autoStopMinutesLabel': 'Auto-Stopp-Timer (Minuten)',
      'scheduledStartOptional': 'Geplanter Start (optional)',
      'scheduledStopOptional': 'Geplanter Stopp (optional)',
      'searchLogs': 'Logs durchsuchen',
      'resumeLogs': 'Logs fortsetzen',
      'pauseLogs': 'Logs pausieren',
      'clearLogs': 'Logs loschen',
      'exportLogs': 'Logs exportieren',
      'all': 'Alle',
      'loggingEnabled': 'Logging aktiviert',
      'loggingDisabledSystem':
        'Logging deaktiviert, ausser Systemereignissen',
      'client': 'Client',
      'jsonImportExport': 'JSON Import/Export',
      'exportAllBrokers': 'Alle Broker exportieren',
      'importBrokers': 'Broker importieren',
      'exportConfig': 'Konfiguration exportieren',
      'importedConfigs': '{count} Broker-Konfigurationen importiert.',
      'about': 'Uber',
      'aboutText':
        'MQTT HUB fuhrt leichte MQTT-Broker direkt auf dem iPhone aus.',
      'networkStateWarning':
        'iOS kann Sockets unterbrechen, während die App im Hintergrund läuft oder der Bildschirm gesperrt ist. MQTT HUB versucht, nach dem Aufwachen zu recover, aber die Betriebszeit des Brokers im Hintergrund kann vom Betriebssystem nicht garantiert werden.',
      'exportsShareDescription':
        'Exporte werden uber das iOS Share Sheet gemeinsam genutzt, das AirDrop, die Dateien-App und andere Ziele unterstutzt.',
      'networkDiagnostics': 'Netzwerkdiagnose',
      'rawPacketMonitor': 'Rohpaket-Monitor',
      'noRawPackets': 'Noch keine rohen MQTT-Frames erfasst.',
      'internalBrokerState': 'Interner Broker-Zustand',
      'language': 'Sprache',
      'maxBrokers': 'Maximale Brokeranzahl',
      'messageRetentionHours': 'Nachrichtenaufbewahrung (Stunden)',
      'maxLogEntries': 'Maximale Logeintrage',
      'appliesToNewBrokers': 'Gilt fur neu erstellte Broker.',
      'statusRunning': 'Lauft',
      'statusStopped': 'Gestoppt',
      'statusStarting': 'Startet',
      'statusError': 'Fehler',
      'modeOffline': 'Offline',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': 'Hotspot',
      'modeCellular': 'Mobilfunk',
      'modeUnknown': 'Unbekannt',
      'languageSystem': 'Systemstandard',
      'langEn': 'Englisch',
      'langRu': 'Russisch',
      'langEs': 'Spanisch',
      'langFr': 'Franzosisch',
      'langDe': 'Deutsch',
      'langZh': 'Chinesisch',
      'langAr': 'Arabisch',
      'retry': 'Erneut versuchen',
      'failedInit':
        'Die App-Dienste konnten nicht initialisiert werden.',
    },
    'zh': {
      'appTitle': 'MQTT HUB',
      'brokers': '代理',
      'importExport': '导入 / 导出',
      'debug': '调试',
      'settings': '设置',
      'refreshNetwork': '刷新网络状态',
      'createBroker': '创建代理',
      'portInUse': '该端口已被其他代理占用。',
      'networkSnapshot': '网络快照',
      'mode': '模式',
      'localIp': '本地 IP',
      'publicIp': '公网 IP',
      'wifi': 'Wi-Fi',
      'unavailable': '不可用',
      'unknown': '未知',
      'noBrokers': '还没有创建代理。请点击“创建代理”。',
      'port': '端口',
      'clients': '客户端',
      'lastActivity': '最近活动',
      'noActivity': '无活动',
      'start': '启动',
      'stop': '停止',
      'restart': '重启',
      'open': '打开',
      'edit': '编辑',
      'duplicate': '复制',
      'delete': '删除',
      'save': '保存',
      'deleteBroker': '删除代理',
      'cancel': '取消',
      'overview': '概览',
      'logs': '日志',
      'brokerSettings': '代理设置',
      'brokerNotFound': '未找到代理',
      'exportBrokerConfig': '导出代理配置',
      'editBroker': '编辑代理',
      'general': '通用',
      'brokerName': '代理名称',
      'description': '描述',
      'currentUptime': '当前运行时长',
      'currentStatus': '当前状态',
      'security': '安全',
      'network': '网络',
      'automationLogging': '自动化与日志',
      'logging': '日志',
      'enabled': '已启用',
      'disabled': '已禁用',
      'anonymousMode': '匿名模式',
      'username': '用户名',
      'password': '密码',
      'allowedClients': '允许的客户端',
      'deniedClients': '拒绝的客户端',
      'notSet': '未设置',
      'anyClient': '任意客户端',
      'none': '无',
      'autoStart': '自动启动',
      'autoStopTimer': '自动停止计时器',
      'autoRestartCrash': '崩溃后自动重启',
      'scheduledStart': '计划启动',
      'scheduledStop': '计划停止',
      'logSizeLimit': '日志大小限制',
      'savePayloads': '保存 payload',
      'websocketPlaceholder': '启用 WebSocket 占位项',
      'configPersistedLater': '该配置将保存，供后续实现使用。',
      'allowExternalAccess': '允许外部访问',
      'localNetworkOnly': '仅本地网络',
      'hotspotSupport': '支持热点模式',
      'autoStartOnLaunch': '启动时自动运行',
      'autoRestartOnCrash': '崩溃时自动重启',
      'enableLogs': '启用日志',
      'allowClientList': '允许客户端列表',
      'denyClientList': '拒绝客户端列表',
      'autoStopMinutesLabel': '自动停止（分钟）',
      'scheduledStartOptional': '计划启动（可选）',
      'scheduledStopOptional': '计划停止（可选）',
      'searchLogs': '搜索日志',
      'resumeLogs': '恢复日志',
      'pauseLogs': '暂停日志',
      'clearLogs': '清空日志',
      'exportLogs': '导出日志',
      'all': '全部',
      'loggingEnabled': '日志已启用',
      'loggingDisabledSystem': '日志已禁用，仅保留系统事件',
      'client': '客户端',
      'jsonImportExport': 'JSON 导入/导出',
      'exportAllBrokers': '导出所有代理',
      'importBrokers': '导入代理',
      'exportConfig': '导出配置',
      'importedConfigs': '已导入 {count} 个代理配置。',
      'about': '关于',
      'aboutText': 'MQTT HUB 可在 iPhone 上直接运行轻量级 MQTT 代理。',
      'networkStateWarning':
        'iOS 可能会在应用在后台运行或屏幕被锁定时暂停套接字。MQTT HUB 尝试在唤醒时恢复，但后台代理的运行时间无法由操作系统保证。',
      'exportsShareDescription':
        '导出通过 iOS 共享表格共享，支持 AirDrop、Files 应用和其他目标。',
      'networkDiagnostics': '网络诊断',
      'rawPacketMonitor': '原始数据包监视器',
      'noRawPackets': '尚未捕获原始 MQTT 数据帧。',
      'internalBrokerState': '内部代理状态',
      'language': '语言',
      'maxBrokers': '最大代理数量',
      'messageRetentionHours': '消息保留时长(小时)',
      'maxLogEntries': '最大日志条数',
      'appliesToNewBrokers': '将应用于新建代理。',
      'statusRunning': '运行中',
      'statusStopped': '已停止',
      'statusStarting': '启动中',
      'statusError': '错误',
      'modeOffline': '离线',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': '热点',
      'modeCellular': '蜂窝网络',
      'modeUnknown': '未知',
      'languageSystem': '系统默认',
      'langEn': '英语',
      'langRu': '俄语',
      'langEs': '西班牙语',
      'langFr': '法语',
      'langDe': '德语',
      'langZh': '中文',
      'langAr': '阿拉伯语',
      'retry': '重试',
      'failedInit': '应用服务初始化失败。',
    },
    'ar': {
      'appTitle': 'MQTT HUB',
      'brokers': 'الوسطاء',
      'importExport': 'استيراد / تصدير',
      'debug': 'تصحيح',
      'settings': 'الإعدادات',
      'refreshNetwork': 'تحديث حالة الشبكة',
      'createBroker': 'إنشاء وسيط',
      'portInUse': 'هذا المنفذ مستخدم بالفعل بواسطة وسيط آخر.',
      'networkSnapshot': 'حالة الشبكة',
      'mode': 'الوضع',
      'localIp': 'IP المحلي',
      'publicIp': 'IP العام',
      'wifi': 'Wi-Fi',
      'unavailable': 'غير متاح',
      'unknown': 'غير معروف',
      'noBrokers': 'لا توجد وسطاء بعد. استخدم إنشاء وسيط للبدء.',
      'port': 'المنفذ',
      'clients': 'العملاء',
      'lastActivity': 'آخر نشاط',
      'noActivity': 'لا يوجد نشاط',
      'start': 'تشغيل',
      'stop': 'إيقاف',
      'restart': 'إعادة تشغيل',
      'open': 'فتح',
      'edit': 'تعديل',
      'duplicate': 'نسخ',
      'delete': 'حذف',
      'save': 'حفظ',
      'deleteBroker': 'حذف الوسيط',
      'cancel': 'إلغاء',
      'overview': 'نظرة عامة',
      'logs': 'السجلات',
      'brokerSettings': 'إعدادات الوسيط',
      'brokerNotFound': 'لم يتم العثور على الوسيط',
      'exportBrokerConfig': 'تصدير إعدادات الوسيط',
      'editBroker': 'تعديل الوسيط',
      'general': 'عام',
      'brokerName': 'اسم الوسيط',
      'description': 'الوصف',
      'currentUptime': 'مدة التشغيل الحالية',
      'currentStatus': 'الحالة الحالية',
      'security': 'الأمان',
      'network': 'الشبكة',
      'automationLogging': 'الأتمتة والسجلات',
      'logging': 'السجلات',
      'enabled': 'مفعل',
      'disabled': 'معطل',
      'anonymousMode': 'الوضع المجهول',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'allowedClients': 'العملاء المسموحون',
      'deniedClients': 'العملاء المرفوضون',
      'notSet': 'غير محدد',
      'anyClient': 'أي عميل',
      'none': 'لا يوجد',
      'autoStart': 'بدء تلقائي',
      'autoStopTimer': 'مؤقت الإيقاف التلقائي',
      'autoRestartCrash': 'إعادة تشغيل تلقائية عند التعطل',
      'scheduledStart': 'بدء مجدول',
      'scheduledStop': 'إيقاف مجدول',
      'logSizeLimit': 'حد السجلات',
      'savePayloads': 'حفظ payloads',
      'websocketPlaceholder': 'تفعيل WebSocket placeholder',
      'configPersistedLater': 'يتم حفظ الإعدادات لتنفيذها لاحقا.',
      'allowExternalAccess': 'السماح بالوصول الخارجي',
      'localNetworkOnly': 'الشبكة المحلية فقط',
      'hotspotSupport': 'دعم وضع نقطة الاتصال',
      'autoStartOnLaunch': 'بدء تلقائي عند التشغيل',
      'autoRestartOnCrash': 'إعادة تشغيل تلقائية عند التعطل',
      'enableLogs': 'تفعيل السجلات',
      'allowClientList': 'قائمة العملاء المسموحين',
      'denyClientList': 'قائمة العملاء المرفوضين',
      'autoStopMinutesLabel': 'الإيقاف التلقائي (دقائق)',
      'scheduledStartOptional': 'بدء مجدول (اختياري)',
      'scheduledStopOptional': 'إيقاف مجدول (اختياري)',
      'searchLogs': 'بحث في السجلات',
      'resumeLogs': 'استئناف السجلات',
      'pauseLogs': 'إيقاف السجلات مؤقتا',
      'clearLogs': 'مسح السجلات',
      'exportLogs': 'تصدير السجلات',
      'all': 'الكل',
      'loggingEnabled': 'السجلات مفعلة',
      'loggingDisabledSystem': 'السجلات معطلة ما عدا أحداث النظام',
      'client': 'العميل',
      'jsonImportExport': 'استيراد/تصدير JSON',
      'exportAllBrokers': 'تصدير جميع الوسطاء',
      'importBrokers': 'استيراد الوسطاء',
      'exportConfig': 'تصدير الإعدادات',
      'importedConfigs': 'تم استيراد {count} إعدادات وسيط.',
      'about': 'حول',
      'aboutText': 'يقوم MQTT HUB بتشغيل وسطاء MQTT خفيفين مباشرة على iPhone.',
      'networkStateWarning':
        'قد يعلق نظام iOS المقابس أثناء وجود التطبيق في الخلفية أو قفل الشاشة. يحاول MQTT HUB الاسترجاع عند الاستيقاظ، لكن وقت تشغيل الوسيط في الخلفية لا يمكن ضمانه من قبل نظام التشغيل.',
      'exportsShareDescription':
        'يتم مشاركة الصادرات عبر ورقة المشاركة في iOS، والتي تسمح بـ AirDrop وتطبيق الملفات والأهداف الأخرى.',
      'networkDiagnostics': 'تشخيص الشبكة',
      'rawPacketMonitor': 'مراقب الحزم الخام',
      'noRawPackets': 'لم يتم التقاط إطارات MQTT خام بعد.',
      'internalBrokerState': 'الحالة الداخلية للوسيط',
      'language': 'اللغة',
      'maxBrokers': 'الحد الأقصى للوسطاء',
      'messageRetentionHours': 'مدة الاحتفاظ بالرسائل (ساعات)',
      'maxLogEntries': 'الحد الأقصى للسجلات',
      'appliesToNewBrokers': 'يطبق على الوسطاء الجدد.',
      'statusRunning': 'يعمل',
      'statusStopped': 'متوقف',
      'statusStarting': 'قيد البدء',
      'statusError': 'خطأ',
      'modeOffline': 'غير متصل',
      'modeWifi': 'Wi-Fi',
      'modeHotspot': 'نقطة اتصال',
      'modeCellular': 'خلوي',
      'modeUnknown': 'غير معروف',
      'languageSystem': 'افتراضي النظام',
      'langEn': 'الإنجليزية',
      'langRu': 'الروسية',
      'langEs': 'الإسبانية',
      'langFr': 'الفرنسية',
      'langDe': 'الألمانية',
      'langZh': 'الصينية',
      'langAr': 'العربية',
      'retry': 'إعادة المحاولة',
      'failedInit': 'فشل تهيئة خدمات التطبيق.',
    },
  };

  String t(String key) {
    final lang = _localizedValues[locale.languageCode];
    return lang?[key] ?? _localizedValues['en']![key] ?? key;
  }

  String importedConfigs(int count) =>
      t('importedConfigs').replaceAll('{count}', '$count');

  String deletePrompt(String name, int port) {
    return switch (locale.languageCode) {
      'ru' => 'Удалить $name на порту $port?',
      'es' => '¿Eliminar $name en el puerto $port?',
      'fr' => 'Supprimer $name sur le port $port ?',
      'de' => '$name auf Port $port loschen?',
      'zh' => '删除 $name（端口 $port）？',
      'ar' => 'حذف $name على المنفذ $port؟',
      _ => 'Delete $name on port $port?',
    };
  }

  String minutes(int value) {
    return switch (locale.languageCode) {
      'ru' => '$value мин',
      'es' => '$value min',
      'fr' => '$value min',
      'de' => '$value Min',
      'zh' => '$value 分钟',
      'ar' => '$value دقيقة',
      _ => value == 1 ? '1 minute' : '$value minutes',
    };
  }

  String uptime(Duration uptime) {
    final hours = uptime.inHours;
    final minutes = uptime.inMinutes.remainder(60);
    final seconds = uptime.inSeconds.remainder(60);
    return switch (locale.languageCode) {
      'ru' => '$hours ч $minutes м $seconds с',
      'es' => '$hours h $minutes m $seconds s',
      'fr' => '$hours h $minutes m $seconds s',
      'de' => '$hours h $minutes m $seconds s',
      'zh' => '$hours 时 $minutes 分 $seconds 秒',
      'ar' => '$hours س $minutes د $seconds ث',
      _ => '$hours h $minutes m $seconds s',
    };
  }

  String languageName(String code) {
    return switch (code) {
      'system' => t('languageSystem'),
      'en' => t('langEn'),
      'ru' => t('langRu'),
      'es' => t('langEs'),
      'fr' => t('langFr'),
      'de' => t('langDe'),
      'zh' => t('langZh'),
      'ar' => t('langAr'),
      _ => t('langEn'),
    };
  }

  /// Returns language name in its native language (not translated to current locale)
  String nativeLanguageName(String code) {
    return switch (code) {
      'system' => t('languageSystem'),
      'en' => 'English',
      'ru' => 'Русский',
      'es' => 'Español',
      'fr' => 'Français',
      'de' => 'Deutsch',
      'zh' => '中文',
      'ar' => 'العربية',
      _ => 'English',
    };
  }

  String statusLabel(BrokerStatus status) {
    return switch (status) {
      BrokerStatus.running => t('statusRunning'),
      BrokerStatus.stopped => t('statusStopped'),
      BrokerStatus.starting => t('statusStarting'),
      BrokerStatus.error => t('statusError'),
    };
  }

  String networkModeLabel(NetworkMode mode) {
    return switch (mode) {
      NetworkMode.offline => t('modeOffline'),
      NetworkMode.wifi => t('modeWifi'),
      NetworkMode.hotspot => t('modeHotspot'),
      NetworkMode.cellular => t('modeCellular'),
      NetworkMode.unknown => t('modeUnknown'),
    };
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any(
        (supported) => supported.languageCode == locale.languageCode,
      );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
